This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things.

All personally identifying information has been removed from the data.

Reference- https://www.kaggle.com/jessemostipak/hotel-booking-demand

In [1]:
import pandas as pd
import numpy as np
import yaml
import json
import os
import pymongo
from pymongo import MongoClient

In [3]:
hb = pd.read_csv("resources/hotel_bookings.csv")
hb

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July                        27   
3                    July                        27   
4                    July                        27   
...                   ...                       ...   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0   
1                               1                        0   
2                               1                        0   
3                               1                        0   
4                               1                        0   
...                           ...                      ...   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
0                          0       2  ...    No Deposit    NaN     NaN   
1                          0       2  ...    No Deposit    NaN     NaN   
2                          1       1  ...    No Deposit    NaN     NaN   
3                          1       1  ...    No Deposit  304.0     NaN   
4                          2       2  ...    No Deposit  240.0     NaN   
...                      ...     ...  ...           ...    ...     ...   
119385                     5       2  ...    No Deposit  394.0     NaN   
119386                     5       3  ...    No Deposit    9.0     NaN   
119387                     5       2  ...    No Deposit    9.0     NaN   
119388                     5       2  ...    No Deposit   89.0     NaN   
119389                     7       2  ...    No Deposit    9.0     NaN   

       days_in_waiting_list customer_type     adr  \
0                         0     Transient    0.00   
1                         0     Transient    0.00   
2                         0     Transient   75.00   
3                         0     Transient   75.00   
4                         0     Transient   98.00   
...                     ...           ...     ...   
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0   
1                                 0                          0   
2                                 0                          0   
3             

In [4]:
list(hb.columns)


['hotel',
 'is_canceled',
 'lead_time',
 'arrival_date_year',
 'arrival_date_month',
 'arrival_date_week_number',
 'arrival_date_day_of_month',
 'stays_in_weekend_nights',
 'stays_in_week_nights',
 'adults',
 'children',
 'babies',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'is_repeated_guest',
 'previous_cancellations',
 'previous_bookings_not_canceled',
 'reserved_room_type',
 'assigned_room_type',
 'booking_changes',
 'deposit_type',
 'agent',
 'company',
 'days_in_waiting_list',
 'customer_type',
 'adr',
 'required_car_parking_spaces',
 'total_of_special_requests',
 'reservation_status',
 'reservation_status_date']

In [ ]:
hb.to_csv("resources/hb.csv", index=True)

In [5]:
#hb.corr()
reduced_hb = hb[["is_canceled", "lead_time", "arrival_date_week_number", "stays_in_weekend_nights", "country"]]
reduced_hb.head()

is_canceled  lead_time  arrival_date_week_number  stays_in_weekend_nights  \
0            0        342                        27                        0   
1            0        737                        27                        0   
2            0          7                        27                        0   
3            0         13                        27                        0   
4            0         14                        27                        0   

  country  
0     PRT  
1     PRT  
2     GBR  
3     GBR  
4     GBR

In [6]:
reduced_hb.to_csv("resources/reduced_hb.csv", index=True)

In [7]:
data = reduced_hb.values
x = data[:, 1:4]
y = data[:, 0]

In [8]:
x

array([[342, 27, 0],
       [737, 27, 0],
       [7, 27, 0],
       ...,
       [34, 35, 2],
       [109, 35, 2],
       [205, 35, 2]], dtype=object)

In [9]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

In [12]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original Class: 0
Encoded Label: 0
------------
Original

In [13]:
from keras.utils import to_categorical

# Step 2: One-hot encoding
one_hot_y = to_categorical(encoded_y)
one_hot_y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [15]:
X_train

array([[175, 30, 1],
       [72, 53, 2],
       [16, 11, 14],
       ...,
       [50, 17, 2],
       [0, 39, 0],
       [120, 40, 0]], dtype=object)

In [16]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)

In [17]:
#scaling
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
X_train_scaled

array([[ 0.66552536,  0.20800091,  0.07239797],
       [-0.29927082,  1.90054398,  1.07481939],
       [-0.8238202 , -1.19018684, 13.10387637],
       ...,
       [-0.50534379, -0.74865387,  1.07481939],
       [-0.97369145,  0.87030037, -0.93002344],
       [ 0.15034294,  0.9438892 , -0.93002344]])

One-hot encode the labels

In [19]:
from tensorflow.keras.utils import to_categorical

In [20]:
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)
y_train_categorical

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

Defining our Model Architecture (the layers)
We first need to create a sequential model

In [21]:
from tensorflow.keras.models import Sequential

model = Sequential()

Next, we add our first layer. This layer requires you to specify both the number of inputs and the number of nodes that you want in the hidden layer.

In [22]:
from tensorflow.keras.layers import Dense
number_inputs = 3
number_hidden_nodes = 4
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))

In [23]:
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax'))

In [ ]:
model.summary()

Compile the Model
Now that we have our model architecture defined, we must compile the model using a loss function and optimizer. We can also specify additional training metrics such as accuracy.

In [24]:
# Use categorical crossentropy for categorical data and mean squared error for regression
# Hint: your output layer in this example is using software for logistic regression (categorical)
# If your output layer activation was `linear` then you may want to use `mse` for loss
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

Training the Model
Finally, we train our model using our training data

In [25]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
2799/2799 - 1s - loss: 0.6165 - accuracy: 0.6639
Epoch 2/100
2799/2799 - 1s - loss: 0.6058 - accuracy: 0.6666
Epoch 3/100
2799/2799 - 1s - loss: 0.6032 - accuracy: 0.6663
Epoch 4/100
2799/2799 - 1s - loss: 0.6015 - accuracy: 0.6672
Epoch 5/100
2799/2799 - 1s - loss: 0.6002 - accuracy: 0.6683
Epoch 6/100
2799/2799 - 1s - loss: 0.5988 - accuracy: 0.6696
Epoch 7/100
2799/2799 - 1s - loss: 0.5977 - accuracy: 0.6697
Epoch 8/100
2799/2799 - 1s - loss: 0.5968 - accuracy: 0.6705
Epoch 9/100
2799/2799 - 1s - loss: 0.5964 - accuracy: 0.6706
Epoch 10/100
2799/2799 - 1s - loss: 0.5961 - accuracy: 0.6706
Epoch 11/100
2799/2799 - 1s - loss: 0.5959 - accuracy: 0.6701
Epoch 12/100
2799/2799 - 1s - loss: 0.5958 - accuracy: 0.6708
Epoch 13/100
2799/2799 - 1s - loss: 0.5955 - accuracy: 0.6709
Epoch 14/100
2799/2799 - 1s - loss: 0.5955 - accuracy: 0.6704
Epoch 15/100
2799/2799 - 1s - loss: 0.5955 - accuracy: 0.6709
Epoch 16/100
2799/2799 - 1s - loss: 0.5954 - accuracy: 0.6706
Epoch 17/100
2799

Quantifying the Model
We use our testing data to validate our model. This is how we determine the validity of our model (i.e. the ability to predict new and previously unseen data points)

In [26]:
# Evaluate the model using the testing data
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

933/933 - 0s - loss: 0.5936 - accuracy: 0.6726
Loss: 0.5935981869697571, Accuracy: 0.6726078987121582


Making Predictions with new data
We can use our trained model to make predictions using model.predict

In [31]:
import numpy as np   # these are not the columns- values of the position of the rows

#make a new prediction- lead= 33, weeknumber = 25, weekend days = 1
new_data = np.array([[33, 25, 1]])
# need to transform the data so model can predict
new_data_scaled = X_scaler.transform(new_data)
# this is our prediction
print(f"Predicted class: {model.predict_classes(new_data_scaled)}")


Predicted class: [0]


In [32]:
# lets predict with test data. first 5 values- different data from above- new prediction
predictions = model.predict_classes(X_test_scaled[:5])
predictions

array([1, 0, 1, 0, 0], dtype=int64)

In [33]:
# this is the actuals from the y_trained data
actuals = list(y_train_categorical[:5])
actuals

[array([1., 0.], dtype=float32),
 array([0., 1.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32),
 array([1., 0.], dtype=float32)]

In [30]:
# first 5 line of x_test data- actual info

X_test[:5]

array([[238, 37, 0],
       [33, 25, 1],
       [239, 42, 0],
       [64, 39, 0],
       [34, 41, 2]], dtype=object)

In [ ]:
model.save("resources/model.h5")